{% set name = "PyLEMS" %}
{% set version = "0.6.8" %}
{% set sha256 = "940ffac3c05d5987db09060fe13297d40ebe9d3a8ac9281be15122eb3d7aaaa1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - lxml
    - typing

test:
  requires:
    - python {{ python_min }}
  imports:
    - lems
    - lems.base
    - lems.dlems
    - lems.model
    - lems.parser
    - lems.sim
  commands:
    - pylems -h

about:
  home: https://github.com/LEMS/pylems
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.lesser
  summary: A Python library for working with the Low Entropy Model Specification language (LEMS)
  dev_url: https://github.com/LEMS/pylems

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
