{% set name = "PyLEMS" %}
{% set version = "0.5.8" %}
{% set sha256 = "8460b315cbf3249c568e523095604a450fb8874714ec59c02a531b66f6a652d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - lxml
    - typing

test:
  imports:
    - lems
    - lems.base
    - lems.dlems
    - lems.model
    - lems.parser
    - lems.sim
  commands:
    - pylems -h

about:
  home: https://github.com/LEMS/pylems
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.lesser
  summary: A Python library for working with the Low Entropy Model Specification language (LEMS)
  dev_url: https://github.com/LEMS/pylems

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
