{% set name = "PyLEMS" %}
{% set version = "0.6.7" %}
{% set sha256 = "b82b66dbe51206b6c3db915651aadfeb6e8eeb5a95d3114ca8b97725f2fafce6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - lxml
    - typing

test:
  requires:
    - python {{ python_min }}
  imports:
    - lems
    - lems.base
    - lems.dlems
    - lems.model
    - lems.parser
    - lems.sim
  commands:
    - pylems -h

about:
  home: https://github.com/LEMS/pylems
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.lesser
  summary: A Python library for working with the Low Entropy Model Specification language (LEMS)
  dev_url: https://github.com/LEMS/pylems

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
