{% set name = "PyLEMS" %}
{% set version = "0.5.1" %}
{% set sha256 = "a43a24374ecb3243a131081c67fbd2a784f3a9d4137eb4fd2436ede6f44c474e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - lems
    - lems.base
    - lems.dlems
    - lems.model
    - lems.parser
    - lems.sim
  commands:
    - pylems -h

about:
  home: https://github.com/LEMS/pylems
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.lesser
  summary: A Python library for working with the Low Entropy Model Specification language (LEMS)
  dev_url: https://github.com/LEMS/pylems

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
