travis:
  secure:
    BINSTAR_TOKEN: dZN7ePe6U8Vek5YiKBWVVru6qqcFHJ6W4LbL1kTVAjXx1zPs0RHnNkFGA2lHaYcQTDGWYv6ZXjxgnZ/y/mqFPN5CVkkC5tl4qraOyUDqF9wihRiLbjwxz1wgf0wij2N6dOFF9ofMI1JuDKLXRb28IO/zNOnhXz3L+uMuMvpgeLWV6V4MQebrDCrBF7nDrBgmoXozAUUiUiJTSFwkxtewxNthuFuFEnH4lJ1ZRPZ/JBL3YHPcsNTldxDirrVEtm9MDzqvsVckZU0DBoAOob17NrEnStPCOQzX9hx7fG2X0kVyLy9A1PfrYTLrwIiUXpoLS0Yy4IF0BJ2V3vBElDR1lohLSi7dYx6+b7zPq8RKabgZk9j22v9C+Uqg0RxeU5vNekRSLBjlyCYzRl2nfyf6D02O9MsQfQUcsn4gO7b5LcUarbjaudareWy1ph4mbI//oZSPXHbAw/kAEj0EJElUL5JE2vuLn5oabuisODjauokK/HiNMN/yWIvr/02/+ns1pO0vIjrqXu1qj58MpHSmkeB86wedK5AEHnIjiXWaZeDqUX0//ZHum7jTFBLSLIFv4W96LPcKSbqsIvIx6Y8KqBUmcLiDIQ38V3j6jJgNUpbxGIVAtllSnmg018gE64bA5JiFVkuHO4PcXi8FTeX1OOe4trw1HpK/m9h5ZEQoFNY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
