travis:
  secure:
    BINSTAR_TOKEN: ZsbLLx4eyegIGvOW10Te4JaCmhB3+pL0QwCMIMzaNVa0V75axDSxblj2+84j3kJ7un1fGVZxlxDtuJeXUpsPsTk9zlFguPql43ejg3N9Qo4xgH2PSKgbJ7CrvtLI9ps5qe8ohP14BQOVgZcicuzejXjbFYSiMBeVXTotO7paXQA/uo9lnroe4dEnjwHcjy/xJOqy9xISsS2FUTuGYgRD5SwWcUpf4bSY7+4VDFDPx4UGZCVtF7DBWWEqadBfNGESsyztUH/xcWOZE+aiCe5GhcwswA68rbYg2564NRyXpnO0r1unTUh6Wnj2UeyxkpEAI4k2Y9VHvjV0H4HZCopxrrJoVa8bMfF15Te1R+4E8Xk9gERi9kvYYhdoo++1o9IG75hCCnCd7R5IngG0m/Ht0dB730NhyfWlY7raJ0JoGN/JdNOeT/d1xZuS0r9gVOHOu4LlnZBTtLTKMN5Nkl/ZA+JC+tGwG2Qo4944juuzAp50XJ4/FqDF6flbQdlY1cN66mju4ho3NX1J94g5dhuWlqDMfKjt8E4ahAdjuYTIIXD7RHPMFomidDO7MY/xqPxqVC5bG3noia5OKfcXF2nDWPomGrcXZIISpJUqOg+TtK7xbGsbIe6CBXyGRNR6KQLkw1pvZBe8cIYT+9RLSdKT9DYZWTTDcaB1PPxdBLsT8tQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
